### ISSUE TITLE
Conditional is marked as unsafe, and cannot be evaluated.

### ISSUE THREAD

**Issue by bashfulrobot** [MusicDin/kubitect#170]
Hi there, I am just starting to test `kubitect`, and ran into an error when deploying a test cluster.

## Deploy Commands

```
kubitect export preset --name example-multi-worker > cluster.yaml
kubitect apply --config cluster.yaml
```

## Error

```
TASK [kubernetes/preinstall : Check /usr readonly] *****************************
ok: [k8s-cluster-master-1]
ok: [k8s-cluster-worker-1]
fatal: [k8s-cluster-master-1]: FAILED! =>
  msg: 'The conditional check ''groups.get(''kube_control_plane'')'' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated.'

TASK [kubernetes/preinstall : Stop if either kube_control_plane or kube_node group is empty] ***

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
k8s-cluster-master-1       : ok=47   changed=3    unreachable=0    failed=1    skipped=56   rescued=0    ignored=0
k8s-cluster-worker-1       : ok=46   changed=3    unreachable=0    failed=0    skipped=45   rescued=0    ignored=0
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

┌
│ Error: ansible-playbook (cluster.yml): Error during command execution: ansible-playbook error: one or more host
│ failed
│
│ Command executed:
│ /home/dustin/.kubitect/share/venv/kubespray/v2.23.1/bin/ansible-playbook --extra-vars {"kube_version":"v1.27.5"}
│ --forks 50 --inventory /home/dustin/.kubitect/clusters/k8s-cluster/config/nodes.yaml --private-key
│ /home/dustin/.kubitect/clusters/k8s-cluster/config/.ssh/id_rsa --timeout 3000 --user k8s --become
│ /home/dustin/.kubitect/clusters/k8s-cluster/ansible/kubespray/cluster.yml
│
│ Error:
│ exit status 2
```

## cluster.yaml

```
hosts:
  - name: localhost
    connection:
      type: local

cluster:
  name: k8s-cluster
  network:
    mode: nat
    cidr: 192.168.113.0/24
  nodeTemplate:
    user: k8s
    updateOnBoot: true
    ssh:
      addToKnownHosts: true
    os:
      distro: ubuntu22
  nodes:
    master:
      default:
        ram: 4
        cpu: 2
        mainDiskSize: 32
      instances:
        - id: 1
          ip: 192.168.113.10
    worker:
      default:
        ram: 8
        cpu: 2
        mainDiskSize: 32
      instances:
        - id: 1
          ip: 192.168.113.21
          ram: 4

kubernetes:
  version: v1.27.5
  networkPlugin: calico


```

Any suggestions?

Thank you.
