### ISSUE TITLE
Add support for setting the name of worker VMs

### ISSUE THREAD

**Issue by seumasdunlop** [MusicDin/kubitect#32]
Currently all workers are named `worker-<id>`.  Ideally I'd like to see the concept of node pools (e.g. in [AKS](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools)) but that would mean a major change to the schema.  E.g. what is currently under `nodes.worker` would be moved to `nodes.workers.node-group-x`.   If you think that is worth pursuing we can create a separate issue but as a stop-gap I've added a name field under `instances` so different node types are more visible in kubernetes.

If you're happy to proceed I'll create a pull request for this.

**Comment by MusicDin** [comment]
Hi, 

I really like the idea of node pools and I'm ready to make changes to the schema to fullfil this idea.
This would certainly be a major change, so it could be planned for the `v3.0.0` release.

One possible approach would be to completly replace static configurations with node pools.
Each node pool would have its own configuration, and instead of defining each node individually, only the size of the pool could be defined, as shown in the following example:

```yaml
cluster:
  ...
  nodes:
    ...
    workers:
      <node-pool-1>:
        count: int
        defaults:
          # defaults that apply only to that particular node pool
      <node-pool-2>:
        count: int
        ...
```

With such approach, I see 2 main issues that need to be addressed.
The first issue is how to assign static IP addresses to the virtual machines and the second one is how to determine where (on which host) to deploy each node.

The IP address problem could be solved with IP pools.
For example, an IP pool could be assigned per cluster or per node pool, from which Kubitect selects an IP address for each VM.

```yaml
cluster:
  nodes:
    workers:
      <node-pool>:
        ipPool: "192.168.113.0/24" # or range of ip addresses: "192.168.113.100 - 192.168.113.150"
```


The *hosts* problem could be solved, for example, by specifying *max-resources* for each host. 
In this way, Kubitect could determine which nodes can be deployed on each host. 
Furthermore, this could be supported with host selectors to restrict a particular node pool to a particular set of hosts.

I still think there are more elegant solutions, but this should be a good start.

@seumasdunlop - could you briefly outline how you would implement node pools (configuration example or concept)?
