### ISSUE TITLE
Allow creating data disks in main resource pool

### ISSUE THREAD

**Issue by MusicDin** [MusicDin/kubitect#45]
1. Allow creating data disks in main resource pool.
```yaml
...
cluster:
  nodes:
    <node-type>:
      instances:
        - id: 1
          dataDisks:
              # References main resource pool
            - name: data-volume-1
              pool: main
              size: 256
              # References main resource pool
            - name: data-volume-2
              size: 256
              # References custom data resource pool
            - name: rook-volume
              pool: rook-pool 
              size: 512
```
2. Prevent creation of data resource pools that are named `main`
